# 配置dev环境
spring:
  profiles: dev
  application:
    name: abcms-provider-config
  # 配置spring-data-jpa
  jpa:
    # 指定是否在Spring容器启动时创建表，默认为false
    generate-ddl: true
    # 指定是否在控制台显示SQL语句，默认为false
    show-sql: true
    # 指定应用重启时不重新更新表
    hibernate:
      ddl-auto: none

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///springcloud02?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8084

eureka:
  client:
    service-url:   # 暴露服务中心地址
      defaultZone: http://eureka8400.com:8400/eureka

---
# 配置test环境
spring:
  profiles: test
  application:
    name: abcms-provider-config
  # 配置spring-data-jpa
  jpa:
    # 指定是否在Spring容器启动时创建表，默认为false
    generate-ddl: true
    # 指定是否在控制台显示SQL语句，默认为false
    show-sql: true
    # 指定应用重启时不重新更新表
    hibernate:
      ddl-auto: none

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///springcloud03?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8085

eureka:
  client:
    service-url:   # 暴露服务中心地址
      defaultZone: http://eureka8500.com:8500/eureka