# 配置dev环境
spring:
  profiles: dev
  application:
    name: abcms-consumer-config

feign:
  hystrix:
    enabled: true

server:
  port: 7070

eureka:
  client:
    service-url:   # 暴露服务中心地址
      defaultZone: http://eureka8400.com:8400/eureka

---
# 配置test环境
spring:
  profiles: test
  application:
    name: abcms-consumer-config

feign:
  hystrix:
    enabled: true

server:
  port: 9090

eureka:
  client:
    service-url:   # 暴露服务中心地址
      defaultZone: http://eureka8500.com:8500/eureka